services:
  flask-db-demo:
    image: felask
    restart: always
    ports:
      - "5000:5000"
    networks:
      - flask-db-demo-net
    environment:
      FLASK_DEBUG: True
      FLASK_RUN_PORT: 5000
      FLASK_RUN_HOST: 0.0.0.0
      DATABASE_URL: postgresql://postgres:postgres@db:5432/flask-db-demo
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flask-db-demo
    networks:
      - flask-db-demo-net
networks:
  flask-db-demo-net: